export default {
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    CATEGORY_SCREEN: 'CATEGORY_SCREEN',
    PROFILE_SCREEN: 'PROFILE_SCREEN',
    PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
};